JasonEtco/actions-toolkit

README.md
I added two of my actions which use actions-toolkit to the usage list in the README.
=> Adding Actions to Usage list

package-lock.json, package.json
This PR removes `@octokit/webhooks` from the devDependencies. Really not sure why it was there in the first place 🤔 I've also added some keywords to the `package.json`, because why not.
=> Remove @octokit/webhooks

bin/template/Dockerfile, package-lock.json, package.json, src/store.ts
Tiny fix for yesterday's addition of #30 - this PR adds some default path values if `GITHUB_WORKSPACE` and `GITHUB_WORKFLOW` aren't defined. This can't happen in actual Actions, but can happen when running an Action locally if not all environment variables have been set.
I've also added some comments to the template's Dockerfile.
=> Defaults for store file path

README.md, package-lock.json, package.json, src/index.ts, tests/__snapshots__/context.test.ts.snap, tests/__snapshots__/index.test.ts.snap, tests/fixtures/issues.opened.json, tests/index.test.ts, tests/setup.ts
This PR adds an object of options to the `Toolkit` constructor, currently with only one key:
```ts
export interface ToolkitOptions {
event?: string | string[]
}
```
On `new Toolkit`, we check that the `process.env.GITHUB_EVENT` is in the array of `only` strings. If it is, we log an error and `exit(1)` to fail the action. You can omit this behavior entirely by just not passing a `only` property.
Read more in #36 for the motivation behind this addition.
Closes #36
=> Allow only a list of events

README.md, package-lock.json, package.json, src/exit.ts, src/index.ts, tests/exit.test.ts
This PR adds an `tools.exit` property with three methods, `success`, `neutral` and `failure`. They each take an optional message string:
```js
tools.exit.success()
tools.exit.failure('Something borked!')
```
Closes #35
=> Add methods to exit an action

package.json
**Why?**
https://jestjs.io/docs/en/configuration#testenvironment-string
Jest defaults to running tests in a jsdom environment. Since actions-toolkit code is expected to run in a Node environment, updating this configuration parameter will more closely reflect the expected production environment.
**How?**
N/A
---
=> Use node testEnvironment in Jest instead of jsdom

tests/index.test.ts
**Why?**
@macklinu opened up #56 to track a memory leak warning in tests; this is due to too many calls to `process.on`. This PR mocks `process.on` in the larger test file, `index.test.ts`, where we instantiate a bunch of Toolkit instances; this way we aren't actually registering event handlers 😊 
Closes #56 
---
=> Mock process.on() in tests

.github/actions/publish-release/publish_release, README.md, package-lock.json, package.json, src/get-body.ts, src/index.ts, tests/__snapshots__/context.test.ts.snap, tests/fixtures/issues.opened.json, tests/get-body.test.ts, tests/index.test.ts
**Why?**
Adds `/command` support via a new `#command` method:
```js
/* /deploy this-repo */
tools.command('deploy', arg => {
console.log(args)
})
```
Closes #17 
**How?**
Added a new `#command` method to the Toolkit class.
---
=> Slash commands

README.md, src/context.ts, tests/context.test.ts
The way that `context.issue` and `context.repo` are functions that merge their arguments has been a point of confusion for me quite a bit.
Given that Node supports object spread, and you can achieve the same goal with that, does it make sense for `context.issue` and `context.repo` to just be (frozen) objects, instead? Before I read over the readme in much more detail, it's how I expected it to work, and looks a little more idiomatic to me.
```javascript
const payload = context.issue({body: 'Hello, world!'})
```
vs
```javascript
const payload = {...context.issue, body: 'Hello, world!'}
```
=> Make `context.issue` and `context.repo` objects

src/exit.ts, src/index.ts, tests/exit.test.ts
**Why?**
Noticed this in #63 - the `Toolkit.exit` methods aren't using the fancy logger I worked so hard to implement in #45 😅
**How?**
This PR adds support for a `logger: Signale` to be passed to the `Exit` class constructor. In the `success`, `neutral` and `failure` methods, we now use the logger instead of `console.log`.
---
=> Use logger in exit

src/index.ts, tests/index.test.ts
**Why?**
I accidentally discovered that `Toolkit.run` (#63) doesn't support non-async functions because of its use of `.catch()`. I don't know if this was intentional, but it's easy enough to support synchronous functions that we might as well do it. There are use-cases like checking things against the payload or in the repo that can be synchronous, so we should support those.
This is the error (I added a test to produce it):
```
● Toolkit › .run › runs a non-async function passed to it
TypeError: func(...).catch is not a function
35 |     const tools = new Toolkit(opts)
36 | 
> 37 |     return func(tools).catch(err => {
|                             ^
38 |       tools.exit.failure(err)
39 |     })
40 |   }
at Function.<anonymous> (src/index.ts:37:29)
```
Makes sense, because functions …
=> Support non-async functions in Toolkit.run

README.md, src/index.ts, tests/__snapshots__/index.test.ts.snap, tests/index.test.ts
**Why?**
Its impossible to enforce that your action is running in the appropriate environment. For that reason, I introduced the `events` option in #36 - in a similar vein, this PR introduces the `secrets` option to help Action authors ensure that users of the Action include the relevant secrets, without having to handle that logic.
Closes #65 
**How?**
I've add a new private method `checkRequiredSecrets` that, as you may imagine, checks the secrets passed in the constructor. It's pretty simple:
https://github.com/JasonEtco/actions-toolkit/blob/f4df76b5a076b2521a47bb62f5f40d12f2571a06/src/index.ts#L300-L309
If any of the required secrets are missing, the action will fail and an error message will be logged.
I also unintentionally bloated this PR by moving some tests around and adding …
=> Add `secrets` option

README.md, src/index.ts, tests/__snapshots__/index.test.ts.snap, tests/index.test.ts
It turns out that this causes unnecessary friction, and locks us into a scenario where we depend on every environment variable to exist. In some cases `GITHUB_REF` isn't present. We can omit that one from the list, but I think that this toes the line of being _too_ strict.
=> Revert "Throw on missing env vars"

package-lock.json, package.json, src/@types/signale/index.d.ts, src/index.ts, tests/index.test.ts
**Why?**
I've been wondering why `tools.log.disable()` doesn't work; it's a handy method that would disable the logger in tests. Turns out `Object.assign()` doesn't clone `prototype` methods, so the `wrapLogger` private method that enabled a callable `tools.log` was omitting unbound methods:
```js
// This works
tools.log.info()
// This does not
tools.log.disable()
```
**How?**
`Object.setPrototypeOf` is magical. Unfortunately this required some type declaration merging, because `@types/signale` does not have the `disable()` method.
---
=> Fix missing methods on `tools.log`

src/index.ts
**Why?**
@gr2m pointed out in #70 that we still don't want to warn on a missing `GITHUB_REF` or `GITHUB_TOKEN` environment variables - the former because its not present for every event, and the latter because its an optional secret.
---
=> Remove GITHUB_REF and GITHUB_TOKEN from required env vars

.github/actions/publish-release/publish_release, .github/main.workflow, package.json
**Why?**
The publishing workflow has been broken this whole time because of either a broken workflow or an incorrect file path. I've been using this for beta releases on #62 and its 👌 
**How?**
I've cherry-picked these commits from #62 - figured they deserved their own PR, and it'll help cleanup #62.
Some key changes:
* Removed the `prepare` script, it was causing problems by publishing empty lib folders
* Added a separate `npm run build` Action
* Fixed the path to the `release-workflow-tag` file, which may include `beta` or `next`.
---
=> Fix publish workflow

README.md, src/context.ts, tests/__snapshots__/context.test.ts.snap, tests/context.test.ts, tests/setup.ts
**Why?**
I've learned that not all events come with a `repository` object on the `event.json` - so using `context.repo` becomes broken. Now, this is already handled by the error in the getter, _but_ since all we're doing is getting a `{ owner, repo }` object, we can do so from the `GITHUB_REPOSITORY` environment variable instead!
**How?**
I've swapped out getting the owner and name from the payload to splitting `GITHUB_REPOSITORY` on `'/'`.
This is going to be a breaking change for a lot of tests, so I'm grouping it in with v2.
---
=> Use GITHUB_REPOSITORY for context.repo

package-lock.json, package.json
**Why?**
This PR moves variables type definition packages from `devDependencies` to `dependencies`, so that TypeScript projects can use those types.
---
=> Move signale, minimist, execa types to deps

src/index.ts
**Why?**
Another round of improving types for various things, for better use in Actions written in ~T~HypeScript.
**How?**
Converted `getPackageJSON` and `config` to use generics, to allow passing a type to return that type as an actual object.
---
=> Use generics for some Toolkit methods

README.md
Reading the documentation on actions, it seems that `created` is not a valid workflow configuration. `opened` is.
https://developer.github.com/actions/managing-workflows/workflow-configuration-options/#events-supported-in-workflow-files
**Why?**
**How?**
---
=> Update README.md `created` -> `opened`

.travis.yml
**Why?**
Node.js 12 has been released on `2019-04-23`, so I've added this version to the Travis CI build matrix to run the tests on this version to make sure that everything is working.
---
=> Add Node.js 12 to Travis CI build matrix

README.md
**Why?**
close #94 
Upon further review, there is not a need to specifically mention how headers can be used. Link directly to the documentation is more than helpful.
**How?**
I added a link to the @octokit/graphql repo. I found this documentation not very discoverable and something I will follow up with that project on. But for now, I think adding this link would help in discovering more details on implementing graphql with this library.
---
=> add link to octokit/graphql repo for documentation

README.md, package-lock.json, package.json, src/index.ts, src/inputs.ts, tests/index.test.ts, tests/inputs.test.ts
**Why?**
[@actions/core](https://github.com/actions/toolkit) introduced a couple of new features that reach into the internals of the Actions runner, mostly by using [special commands](https://github.com/actions/toolkit/blob/master/docs/commands.md). I want this library to become a more opinionated wrapper around the official `@actions/*` libraries, so this PR implements a few features of those libraries as part of the `Toolkit` class.
**How?**
The main changes:
* `Toolkit.run` now calls `core.setFailed`, to create a failure annotation.
* `tools.inputs` is a new property - its an instance of [`Proxy`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy/) that operates like an object of the action's inputs. This is the preferred way to get actions' …
=> Wrap @actions/core and enable new features

package-lock.json, package.json, src/index.ts, tests/__snapshots__/index.test.ts.snap, tests/index.test.ts
**Why?**
This PR improves the error message thrown by `Toolkit#getFile`, because of confusion around needing to clone the repo via `actions/checkout`.
**How?**
Notes that you may need the `actions/checkout` action to clone the repository if the file cannot be found.
---
=> Point to actions/checkout if getFile throws

README.md
**Why?**
The current link is 404. 
**How?**
I believe https://help.github.com/en/actions/reference/events-that-trigger-workflows is a correct page now.
---
=> Fix broken actions events link

README.md, src/index.ts
**Why?**
A lot of actions prefer to use inputs over environment variables. They're documented in the `action.yml` file, and you can easily fill in default/required values.
**How?**
This PR changes `Toolkit.token` to consider `inputs.github_token` before falling back to `env.GITHUB_TOKEN`. To be safe, I'm going to make this change a part of `v5`, since it could be breaking for workflows that use `github_token` for other things.
---
=> Support github_token input in addition to env.GITHUB_TOKEN

bin/create-action.js
**Why?**
The words `background color` are used twice in a row in `bin/create-action.js`
**How?**
Removed duplicate words
---
=> Remove duplicate "background color" in CLI

src/exit.ts, tests/index.test.ts
**Why?**
This should help in Typescript control flow analysis.
=> fix: return never from exit functions

src/context.ts
**Why?**
Noticed these types were unhelpful - before, it was returning `{ [key: string]: any }`, because of how we defined `data`.
**How?**
Now we only conditionally define the `issue_number` or `pull_number`, and return a more strict object that includes `context.repo`, so the typing is more specific.
---
=> Improve types for context.issue/pull_request

package.json
**Why?**
[GitHub disclosed a security vulnerability in GitHub Actions](https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/) around `set-env` and `add-path`.
> Action authors who are using the toolkit should update the @actions/core package to v1.2.6 or greater to get the updated addPath and exportVariable functions.
**How?**
This pull request updates the `@actions/core` dependency version to `^1.2.6`, instead of `^1.2.4`, to ensure version `1.2.6` or greater is installed.
`package-lock.json` already has version `1.2.6`.
---
=> Require @actions/core 1.2.6
